rendering: ~
security:  ~

# insert your own filters here
MyCustomFilter:  
  class: MyCustomFilter
  param:
    applicationId: Your Moesif Application Id
    debug: 'true'
    logBody: 'true'

cache:     ~
execution: ~
